### ISSUE TITLE
Do you have an upload example?

### ISSUE THREAD

**Issue by Azuka** [pepipost/pepipost-sdk-php#1]
Do you have an example for making an api call to create an attachment? I believe that's needed to get back the attachment ids to use with the mail.

**Comment by i-tabu** [comment]
The attachments needs to be created by logging into the application (Settings > Customize > Attachments). The attachment id will appear after a successful upload. This id can be used instead of the whole attachment content (base64 encoded) in order to save the bandwidth. The API for the same is in our roadmap :P
